name: dragmesh2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - pyyaml
  - pillow
  - imageio
  - opencv
  - pytorch
  - pytorch-cuda
  - tensorboard
  - pip:
      - open3d
      - gym
      - rl-games
      - tqdm
      - wandb
